### ISSUE TITLE
Support changing email

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#120]
![image](https://user-images.githubusercontent.com/1434248/218320571-6e2e3ec6-6f46-4608-8e65-f3dbdbf2ee29.png)

**Comment by dusekj4** [comment]
starting to work on it with this issue https://github.com/beyond-all-reason/bar-lobby/issues/159

**Comment by p2004a** [comment]
Out of scope for lobby, will need to be handled via website, by design.
