### ISSUE TITLE
Make ready button a ToggleButton with checkbox icon

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#129]

**Comment by JasonReed-2** [comment]
How does this look?
![image](https://github.com/beyond-all-reason/bar-lobby/assets/64571081/65c84ad9-79dd-4e44-86f1-0103df28cbbf)
![image](https://github.com/beyond-all-reason/bar-lobby/assets/64571081/9ce08bae-2aae-48e2-b12a-cf11a611fefd)
