### ISSUE TITLE
New Lobby: !help and $help commands

### ISSUE THREAD

**Issue by Descyphal** [beyond-all-reason/bar-lobby#157]
Very simply, the commands from !help and $help have always needed more intuitive and practical presentation/availability.

perhaps these commands should be listed here:

![commands](https://user-images.githubusercontent.com/128336457/226235149-11b72acb-85e2-4bda-9002-e35bd8b92032.png)

**Comment by dusekj4** [comment]
will look to it

**Comment by Jazcash** [comment]
fixed in https://github.com/beyond-all-reason/bar-lobby/pull/187
