### ISSUE TITLE
Lobby locked or unlocked state

### ISSUE THREAD

**Issue by Descyphal** [beyond-all-reason/bar-lobby#165]
There's no indication for when the room you're in is locked. There's no way to unlock it without typing !unlock, as the locked button does not also unlock.

![lock-team-player](https://user-images.githubusercontent.com/128336457/226781931-85b3de0f-f25c-43ff-ad53-af39c816310d.png)

**Comment by thehobojoe** [comment]
Can you elaborate on this? It works for me, and correctly indicates current state. 

https://user-images.githubusercontent.com/3493638/226755087-b80cf055-ae58-4de6-8637-2eef3ca9013e.mp4

**Comment by Descyphal** [comment]
Seems to be working, now. But it wasn't working before. Inconsistent, i'll report if it breaks again and record it.
