### ISSUE TITLE
Replays 'show spoilers' filter issue

### ISSUE THREAD

**Issue by Descyphal** [beyond-all-reason/bar-lobby#168]
When clicking 'show spoilers', it toggles on/off, but then a third state happens where you cannot click it again to turn it back on, until you move the cursor away from the button.

Also, in the bottom right, the trophy icon goes orange... Not sure what this trophy/outcome means.

**Comment by Jazcash** [comment]
Can't repro this one, either the stuck checkbox or the orange trophy. Gonna close for now
