### ISSUE TITLE
Fatal error clicking multiplayer button

### ISSUE THREAD

**Issue by Descyphal** [beyond-all-reason/bar-lobby#171]
Steps not working to reproduce, but this is exactly what I'd just done:

Client's been active and i've been pressing and inspecting everything, but.. the last things I did, was:

I had my profile selected, 
alt tabbed from client which is in windowed mode to chat to you fine fellas on discord for 90s or so
tabbed back
selected multiplayer and got this:

![image](https://user-images.githubusercontent.com/128336457/226499150-4fb18c93-7e7c-4a6e-bf52-1f5f5a52b997.png)

**Comment by Jazcash** [comment]
Have opened a new issue to track this here: https://github.com/beyond-all-reason/bar-lobby/issues/179
