### ISSUE TITLE
Leaving a game room still shows user

### ISSUE THREAD

**Issue by ArturasNoit** [beyond-all-reason/bar-lobby#174]
After joining and leaving a game room it keeps showing user in that room. 
Tried like 5 rooms, it kept showing my username in all of them.

**Note:** Need to test if this issue shows up for other users too or just for user who repeatedly joins different rooms

**Comment by dusekj4** [comment]
well even if you go to other room without click on leave, you will stay there, i guess if you join to other room it will not remove you from the room you are in, actually you cannot get back to that aditional room

**Comment by dusekj4** [comment]
will look to it
