### ISSUE TITLE
simple markdown support for chat

### ISSUE THREAD

**Issue by drivver44** [beyond-all-reason/bar-lobby#185]
it would be useful for mentors to have markdown formating when it comes to messages
often things like how to rename room follows

* you need to !boss yourself first 
* then do $rename namehere

would be better to look as
 * you need to `!boss` `yourself`
 * then do `$rename`

**Comment by JasonReed-2** [comment]
If we implement this: we should avoid rendering the headers [#]. The larger text could be abused / obnoxious in chat.
