### ISSUE TITLE
Implement command intellisense into the chatbox

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#188]
So you can type `/` and it will bring up a list of every command, along with some helper info as you flick through them, the same as when you do it on discord. Will want to combine SPADS and Server commands (`!` and `$`) together for the visible frontend.

![image](https://user-images.githubusercontent.com/1434248/230491199-3cdaceb5-081d-45a4-bbff-c8133f7e532c.png)

**Comment by WatchTheFort** [comment]
Disagree on this, the player should never have to use any text commands, ever. All functionality needs to be provided as UI elements.

**Comment by thehobojoe** [comment]
> Disagree on this, the player should never have to use any text commands, ever. All functionality needs to be provided as UI elements.

I agree that most of this functionality should exist in the UI. But there are way too many commands to fit all of them in the UI, and even if they could fit, the commands are incredibly quick and powerful ways to control the lobby, myself and many others tend to use the chat commands in chobby even when the tools exist in the UI already. Typing in something like `!map comet` or `!spec name` is simply faster than using the UI. Having a nice autocomplete system will make it even nicer too :)

**Comment by WatchTheFort** [comment]
Text commands sound like something for power users, a normal user should be able to fully utilize the lobby without having to enter them.

It would also be better to have a separate, dedicated console, rather than adding noise to the chat.
