### ISSUE TITLE
Button text gets hidden on overflow

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#194]
![image](https://user-images.githubusercontent.com/1434248/230695908-225865b1-cd67-448f-93a9-a3d1078b22c8.png)

Is an issue for smaller resolution/window size when elements get cramped and start to split lines. This can be fixed by removing the `max-height: 35px;` line in `Control.vue`, but that line was written as a hacky way to make all controls be the same vertical height, for pretty alignment. Instead it might be better for controls to fill their vertical space, but will need to test the whole app to make sure this doesn't break stuff, e.g:

![image](https://user-images.githubusercontent.com/1434248/230696136-e90d9a01-74c7-4d08-921b-d736fc4615a0.png)

The other alternative is forcing button text to always be on same line, then making sure that doesn't break sibling elements from getting pushed off horizontally.

**Comment by dusekj4** [comment]
Maybe the best solutions is the most dumb :) . What about just renamed it to Host.

**Comment by Jazcash** [comment]
> Maybe the best solutions is the most dumb :) . What about just renamed it to Host.

This issue isn't about this button specifically, but how to handle this problem in general

**Comment by 1-alex98** [comment]
Can only reproduce with developer tools. Otherwise min window size keeps this from happening
