### ISSUE TITLE
UI control for changing battle title

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#201]
An often asked question is how to rename a battle. Should implement perhaps some edit button next to battle title that prompts the user to enter a new one.

**Comment by dusekj4** [comment]
is there also api for it allready

**Comment by Jazcash** [comment]
No actually, which makes it a bit awkward because it currently works via the `$rename <title>` server command, and can only be called by a boss or moderator, and there is no data from the server about who's the boss or if there even is one.

**Comment by dusekj4** [comment]
uff

**Comment by 1-alex98** [comment]
@Jazcash $status yields who is boss can i use this info by parsing it?
