### ISSUE TITLE
Multiplayer Custom Battles Runtime should not show seconds

### ISSUE THREAD

**Issue by kozak-codes** [beyond-all-reason/bar-lobby#223]
Since all the timestamps update at a different time, it appears very busy when the runtime is updating. In my opinion, it would clean this up if we just use HH:mm. This is very useful information to determine if a lobby will be restarting soon but seconds are not pertinent to that information.

**Comment by wereii** [comment]
Hmm, is it just me or now it looks like it could be confused with minutes:seconds that are stuck. 

![image](https://github.com/beyond-all-reason/bar-lobby/assets/8504482/4aa35284-aa85-46a5-9042-ab05e645f981)

**Comment by wereii** [comment]
This seems a bit too verbose but does the trick
![image](https://github.com/beyond-all-reason/bar-lobby/assets/8504482/d524ea0c-13ad-4db8-a031-7af5248e420a)
