### ISSUE TITLE
Keyboard selecting an auto-suggestion automatically submits the command

### ISSUE THREAD

**Issue by JasonReed-2** [beyond-all-reason/bar-lobby#253]
**Issue**
When a user uses the keyboard to select an autosuggestion: pressing enter automatically submits the auto-suggestion instead of populating it into the text-box then letting the user submit it themselves.

**Impact**
This is a problem for commands that require the user to enter arguments after the command itself. Example: the "!clusterstatus" command requires you to enter the <clusterName> as an argument after the command.

**Comment by p2004a** [comment]
Deprecated by tachyon protocol in which commands are not going to work like that at all.
