### ISSUE TITLE
Swapping between routes very quickly crashes the Vue renderer

### ISSUE THREAD

**Issue by Jazcash** [beyond-all-reason/bar-lobby#61]
```
Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

Seems easier to repro on multiplayer custom battle list page, possibly related to suspense api

**Comment by Jazcash** [comment]
https://lightrun.com/answers/nuxt-framework-error-when-fast-navigating-failed-to-execute-insertbefore-on-node

**Comment by Jazcash** [comment]
Probably related to https://github.com/vuejs/core/issues/7966#issuecomment-1488801586

**Comment by 1-alex98** [comment]
https://github.com/vuejs/core/issues/8105

**Comment by 1-alex98** [comment]
Removing transition removes the issue 
https://github.com/beyond-all-reason/bar-lobby/blob/b2f3b1ec71e34ac89482904ea8160b14ea885b04/src/renderer/App.vue#L32

**Comment by 1-alex98** [comment]
Maybe we should do that until issue is fixed in vue or we have a better solution

**Comment by 1-alex98** [comment]
Also removing out-in works. Does not look as good tho
