### ISSUE TITLE
Developer mode toggle

### ISSUE THREAD

**Issue by Teifion** [beyond-all-reason/bar-lobby#79]
Would allow users to see more information about what was sent/received. Would be useful for comparing against the server and helping troubleshoot issues as the userbase grows.

**Comment by Jazcash** [comment]
Ctrl+Shift+I to bring up devtools, then enable verbose logging here:
![image](https://user-images.githubusercontent.com/1434248/194753522-50c74f07-71ea-4af2-84ef-82e7e49dc202.png)

Logs all requests/responses apart from ping/pong and server stats watch responses. There's also some custom dev helper stuff in the bottom right but only for the development build atm.
